#!/bin/bash

#
# Block until VNC is listening
#
until netstat -an | grep $PORTNUM | grep -i LISTEN
do
  : > /dev/null
done

# And write out the proof that we're ready
# This is a bit of a lie, but we have no real choice
# since we have to keep websockify running in foreground mode.

(sleep 2; touch /var/spool/docker/$EXT) &

#EXT=eval $PORTNUM + 1
websockify $EXT localhost:$PORTNUM >> /var/spool/docker/$EXT.websockify.out


#
# and on exit, remove the file
#

rm /var/spool/docker/$EXT
